CREATE TABLE vault( id INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY, capacity INTEGER, location VARCHAR(255), defenseLvl INTEGER, foodCap INTEGER, waterCap INTEGER);
INSERT INTO vault(capacity, location, defenseLvl,foodCap,waterCap) VALUES('20', 'Glowing_see', '90','5','10');
INSERT INTO vault(capacity, location, defenseLvl,foodCap,waterCap) VALUES('50', 'Diamond_city', '90','5','10');
INSERT INTO vault(capacity, location, defenseLvl,foodCap,waterCap) VALUES('100', 'Airport', '90','5','10');
INSERT INTO vault(capacity, location, defenseLvl,foodCap,waterCap) VALUES('5', 'Malden', '90','5','10');
INSERT INTO vault(capacity, location, defenseLvl,foodCap,waterCap) VALUES('40', 'Back_bay', '90','5','10');
INSERT INTO vault(capacity, location, defenseLvl,foodCap,waterCap) VALUES('10', 'Derchester', '90','5','10');
INSERT INTO vault(capacity, location, defenseLvl,foodCap,waterCap) VALUES('400', 'Fenway', '90','5','10');
INSERT INTO vault(capacity, location, defenseLvl,foodCap,waterCap) VALUES('1', 'Brighton', '90','5','10');
INSERT INTO vault(capacity, location, defenseLvl,foodCap,waterCap) VALUES('110', 'Lynn', '90','5','10');
INSERT INTO vault(capacity, location, defenseLvl,foodCap,waterCap) VALUES('20', 'Revere', '90','5','10');